insert into Qra6NR535w.roles (role) value ("USER");
insert into Qra6NR535w.roles (role) value ("ADMIN");

insert into Qra6NR535w.actions (name) value ('AdBlue - dodatek do paliwa');
insert into Qra6NR535w.actions (name) value ('Akumulator');
insert into Qra6NR535w.actions (name) value ('Alternator nowy');
insert into Qra6NR535w.actions (name) value ('Alternator regenerowany');
insert into Qra6NR535w.actions (name) value ('Amortyzatory przód');
insert into Qra6NR535w.actions (name) value ('Amortyzatory tył');
insert into Qra6NR535w.actions (name) value ('Antena');
insert into Qra6NR535w.actions (name) value ('Auto zastępcze');
insert into Qra6NR535w.actions (name) value ('Bateria pilota');
insert into Qra6NR535w.actions (name) value ('Bezpiecznik');
insert into Qra6NR535w.actions (name) value ('Bębny hamulcowe');
insert into Qra6NR535w.actions (name) value ('Cewka zapłonowa');
insert into Qra6NR535w.actions (name) value ('Chłodnica');
insert into Qra6NR535w.actions (name) value ('Cylinderek hamulcowy');
insert into Qra6NR535w.actions (name) value ('Cylinderek hamulcowy');
insert into Qra6NR535w.actions (name) value ('Czujnik ABS');
insert into Qra6NR535w.actions (name) value ('Czujnik ciśnienia paliwa');
insert into Qra6NR535w.actions (name) value ('Czujnik filtra cząstek stałych');
insert into Qra6NR535w.actions (name) value ('Czujnik wału korbowego/wałka rozrządu');
insert into Qra6NR535w.actions (name) value ('Czujnik parkowania');
insert into Qra6NR535w.actions (name) value ('Czujnik parkowania');
insert into Qra6NR535w.actions (name) value ('Czyszczenie układu hamulcowego przód');
insert into Qra6NR535w.actions (name) value ('Czyszczenie układu hamulcowego tył');
insert into Qra6NR535w.actions (name) value ('Dezynfekcja klimatyzacji');
insert into Qra6NR535w.actions (name) value ('Diagnostyka');
insert into Qra6NR535w.actions (name) value ('Drążek kierowniczy - lewy');
insert into Qra6NR535w.actions (name) value ('Drążek kierowniczy - prawy');
insert into Qra6NR535w.actions (name) value ('Dysze spryskiwacza szyb');
insert into Qra6NR535w.actions (name) value ('Dywaniki');
insert into Qra6NR535w.actions (name) value ('iltr cząstek stałych');
insert into Qra6NR535w.actions (name) value ('filtr gazu LPG');
insert into Qra6NR535w.actions (name) value ('Filtr paliwa');
insert into Qra6NR535w.actions (name) value ('Filtr powietrza');
insert into Qra6NR535w.actions (name) value ('Filtr pyłkowy');
insert into Qra6NR535w.actions (name) value ('Gaśnica');
insert into Qra6NR535w.actions (name) value ('Głowica silnika');
insert into Qra6NR535w.actions (name) value ('Gumy stabilizatora - przód');
insert into Qra6NR535w.actions (name) value ('Gumy stabilizatora - tył');
insert into Qra6NR535w.actions (name) value ('Inne');
insert into Qra6NR535w.actions (name) value ('Intercooler');
insert into Qra6NR535w.actions (name) value ('Klimatyzacja - opróżnienie/napełnienie');
insert into Qra6NR535w.actions (name) value ('Klocki hamulcowe - przód');
insert into Qra6NR535w.actions (name) value ('Klocki hamulcowe - tył');
insert into Qra6NR535w.actions (name) value ('Kolektor ssący');
insert into Qra6NR535w.actions (name) value ('Kolektor wydechowy');
insert into Qra6NR535w.actions (name) value ('Koło pasowe osprzętu');
insert into Qra6NR535w.actions (name) value ('Koło zamachowe');
insert into Qra6NR535w.actions (name) value ('Kołpak');
insert into Qra6NR535w.actions (name) value ('Końcówka drążka kierowniczego - lewa');
insert into Qra6NR535w.actions (name) value ('Końcówka drążka kierowniczego - prawa');
insert into Qra6NR535w.actions (name) value ('Lampy');
insert into Qra6NR535w.actions (name) value ('Linka hamulca ręcznego');
insert into Qra6NR535w.actions (name) value ('Lusterko zewnętrzne');
insert into Qra6NR535w.actions (name) value ('Łącznik stabilizatora przód - lewy');
insert into Qra6NR535w.actions (name) value ('Łącznik stabilizatora przód - prawy');
insert into Qra6NR535w.actions (name) value ('Łącznik stabilizatora tył - lewy');
insert into Qra6NR535w.actions (name) value ('Łącznik stabilizatora tył - prawy');
insert into Qra6NR535w.actions (name) value ('Łożyska górne amortyzatorów');
insert into Qra6NR535w.actions (name) value ('Łożysko podpory półosi');
insert into Qra6NR535w.actions (name) value ('Mechanizm / silnik wycieraczek');
insert into Qra6NR535w.actions (name) value ('Mechanizm zmiany biegów');
insert into Qra6NR535w.actions (name) value ('Miska olejowa');
insert into Qra6NR535w.actions (name) value ('Montaż bluetooth');
insert into Qra6NR535w.actions (name) value ('Napinacz paska osprzętu');
insert into Qra6NR535w.actions (name) value ('Naprawa instalacji elektrycznej');
insert into Qra6NR535w.actions (name) value ('Olej');
insert into Qra6NR535w.actions (name) value ('Osłona podsilnikowa/Nadkola - uszkodzone');
insert into Qra6NR535w.actions (name) value ('Osłona przegubu');
insert into Qra6NR535w.actions (name) value ('Osłony termiczne wydechu');
insert into Qra6NR535w.actions (name) value ('Paski napędowe osprzętu');
insert into Qra6NR535w.actions (name) value ('Pilot');
insert into Qra6NR535w.actions (name) value ('Pióra wycieraczek / gumki');
insert into Qra6NR535w.actions (name) value ('Płyn chłodzący');
insert into Qra6NR535w.actions (name) value ('Płyn do układu wspomagania');
insert into Qra6NR535w.actions (name) value ('Płyn hamulcowy - wymiana');
insert into Qra6NR535w.actions (name) value ('Poduszka silnika');
insert into Qra6NR535w.actions (name) value ('Poduszka skrzyni biegów');
insert into Qra6NR535w.actions (name) value ('Pompa / przewód wspomagania');
insert into Qra6NR535w.actions (name) value ('Pompa paliwa');
insert into Qra6NR535w.actions (name) value ('Pompa sprzęgła');
insert into Qra6NR535w.actions (name) value ('Pompa wody');
insert into Qra6NR535w.actions (name) value ('Pompa wtryskowa');
insert into Qra6NR535w.actions (name) value ('Półosie napędowe/przeguby napędowe');
insert into Qra6NR535w.actions (name) value ('Przegląd');
insert into Qra6NR535w.actions (name) value ('Przekładnia kierownicza');
insert into Qra6NR535w.actions (name) value ('Przepustnica/przepływomierz');
insert into Qra6NR535w.actions (name) value ('Przewody paliwowe');
insert into Qra6NR535w.actions (name) value ('Przewody układu chłodzenia');
insert into Qra6NR535w.actions (name) value ('Przewód układu klimatyzacji');
insert into Qra6NR535w.actions (name) value ('Przewód wysokiego napięcia');
insert into Qra6NR535w.actions (name) value ('Rozrusznik regeneracja/naprawa');
insert into Qra6NR535w.actions (name) value ('Rozrząd');
insert into Qra6NR535w.actions (name) value ('Rura intercoolera');
insert into Qra6NR535w.actions (name) value ('Silnik / blok silnika');
insert into Qra6NR535w.actions (name) value ('Skraplacz układu klimatyzacji');
insert into Qra6NR535w.actions (name) value ('Skrzynia biegów');
insert into Qra6NR535w.actions (name) value ('Sonda lambda');
insert into Qra6NR535w.actions (name) value ('Sprawdzenie zawieszenia');
insert into Qra6NR535w.actions (name) value ('Sprężarka klimatyzacji');
insert into Qra6NR535w.actions (name) value ('Sprężyna zawieszenia');
insert into Qra6NR535w.actions (name) value ('Spryskiwacz reflektora / zaślepka');
insert into Qra6NR535w.actions (name) value ('Sprzęgło');
insert into Qra6NR535w.actions (name) value ('Stacyjka');
insert into Qra6NR535w.actions (name) value ('Sworzeń wahacza - lewy');
insert into Qra6NR535w.actions (name) value ('Sworzeń wahacza - prawy');
insert into Qra6NR535w.actions (name) value ('Sygnał dźwiękowy - klakson');
insert into Qra6NR535w.actions (name) value ('Syrenka alarmu');
insert into Qra6NR535w.actions (name) value ('Szczęki hamulcowe');
insert into Qra6NR535w.actions (name) value ('Świeca żarowa');
insert into Qra6NR535w.actions (name) value ('Świeca zapłonowa');
insert into Qra6NR535w.actions (name) value ('Tarcze hamulcowe - przód');
insert into Qra6NR535w.actions (name) value ('Tarcze hamulcowe - tył');
insert into Qra6NR535w.actions (name) value ('Termostat');
insert into Qra6NR535w.actions (name) value ('Tłumiki / Łącznik elastyczny');
insert into Qra6NR535w.actions (name) value ('Transport pojazdu - usługa D2D');
insert into Qra6NR535w.actions (name) value ('Turbosprężarka');
insert into Qra6NR535w.actions (name) value ('Uszczelka głowicy silnika');
insert into Qra6NR535w.actions (name) value ('Uszczelka pokrywy zaworów');
insert into Qra6NR535w.actions (name) value ('Uszczelniacze półosi');
insert into Qra6NR535w.actions (name) value ('Uszczelniacze rozrządu/wału');
insert into Qra6NR535w.actions (name) value ('Wahacze zawieszenia');
insert into Qra6NR535w.actions (name) value ('Wentylator / moduł dmuchawy');
insert into Qra6NR535w.actions (name) value ('Wentylator chłodnicy');
insert into Qra6NR535w.actions (name) value ('Wtryskiwacz paliwa');
insert into Qra6NR535w.actions (name) value ('Wymiana oleju - poza przeglądami');
insert into Qra6NR535w.actions (name) value ('Wysprzęglik/łożysko sprzęgłowe');
insert into Qra6NR535w.actions (name) value ('Zacisk hamulcowy - przód');
insert into Qra6NR535w.actions (name) value ('Zacisk hamulcowy - tył');
insert into Qra6NR535w.actions (name) value ('Zamek drzwi, wkładka, kluczyk');
insert into Qra6NR535w.actions (name) value ('Zawór EGR');
insert into Qra6NR535w.actions (name) value ('Zbieżność/geometria');
insert into Qra6NR535w.actions (name) value ('Żarówki oświetlenia zewnętrznego');
insert into Qra6NR535w.actions (name) value ('Żarówki podświetlenia wewnętrznego');

insert into Qra6NR535w.status (name) value ('Dodane');
insert into Qra6NR535w.status (name) value ('Sprawdzone');
insert into Qra6NR535w.status (name) value ('Odrzucone');
insert into Qra6NR535w.status (name) value ('Zakończone');






